
//This code has been automatically generated by DudeLabs LLC RCConverter
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

using System.IO;
using System.Threading;

namespace ConfigEditor
{
	/// <summary>
	/// Summary description for frmDialogHardDriveParameters.
	/// </summary>
	public partial class frmDialogHardDriveParameters : System.Windows.Forms.Form
	{
        public class SupportedWinchesterDrive
        {
            public int bytesPerSector;
            public int cylinders;
            public int heads;
            public int sectorsPerTrack;
        }

        public Dictionary<string, SupportedWinchesterDrive> supportedWinchesterDrives = new Dictionary<string, SupportedWinchesterDrive>
        {
            {"CMI 5619 (19Mb)"  , new SupportedWinchesterDrive {bytesPerSector=0x200, cylinders=0x132, heads=6, sectorsPerTrack=0x11}},
            {"CMI 5640 (40Mb)"  , new SupportedWinchesterDrive {bytesPerSector=0x200, cylinders=0x280, heads=6, sectorsPerTrack=0x11}},
            {"D-514 (RMS)]"     , new SupportedWinchesterDrive {bytesPerSector=0x200, cylinders=0x132, heads=4, sectorsPerTrack=0x11}},
            {"D-526 (RMS)]"     , new SupportedWinchesterDrive {bytesPerSector=0x200, cylinders=0x132, heads=8, sectorsPerTrack=0x11}},
            {"RMS 506]"         , new SupportedWinchesterDrive {bytesPerSector=0x200, cylinders=0x099, heads=4, sectorsPerTrack=0x11}},
            {"RMS 509]"         , new SupportedWinchesterDrive {bytesPerSector=0x200, cylinders=0x0d7, heads=4, sectorsPerTrack=0x11}},
            {"RMS 512]"         , new SupportedWinchesterDrive {bytesPerSector=0x200, cylinders=0x099, heads=8, sectorsPerTrack=0x11}},
            {"RMS 518]"         , new SupportedWinchesterDrive {bytesPerSector=0x200, cylinders=0x0d7, heads=8, sectorsPerTrack=0x11}},
            {"RO 201]"          , new SupportedWinchesterDrive {bytesPerSector=0x200, cylinders=0x141, heads=2, sectorsPerTrack=0x11}},
            {"RO 202]"          , new SupportedWinchesterDrive {bytesPerSector=0x200, cylinders=0x141, heads=4, sectorsPerTrack=0x11}},
            {"RO 203]"          , new SupportedWinchesterDrive {bytesPerSector=0x200, cylinders=0x141, heads=6, sectorsPerTrack=0x11}},
            {"RO 204]"          , new SupportedWinchesterDrive {bytesPerSector=0x200, cylinders=0x141, heads=8, sectorsPerTrack=0x11}},
            {"Rodime RO5090]"   , new SupportedWinchesterDrive {bytesPerSector=0x200, cylinders=0x4c8, heads=7, sectorsPerTrack=0x11}},
            {"ST 412]"          , new SupportedWinchesterDrive {bytesPerSector=0x200, cylinders=0x132, heads=4, sectorsPerTrack=0x11}},
            {"ST 506]"          , new SupportedWinchesterDrive {bytesPerSector=0x200, cylinders=0x099, heads=4, sectorsPerTrack=0x11}},
            {"TMS 503]"         , new SupportedWinchesterDrive {bytesPerSector=0x200, cylinders=0x099, heads=4, sectorsPerTrack=0x11}},
        };

        public string imagePath;
        public string name;
        public int cylinders;
        public int bytesPerSector;
        public int heads;
        public int sectorsPerTrack;

        private string dataDir = "";

		public frmDialogHardDriveParameters(string _dataDir)
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

            dataDir = _dataDir;

            foreach (KeyValuePair<string, SupportedWinchesterDrive> kvp in supportedWinchesterDrives)
            {
                cboComboDefinedDrives.Items.Add(kvp.Key);
            }
        }

        private void frmDialogHardDriveParameters_Load(object sender, EventArgs e)
        {
            txtEditPath.Text = imagePath;
            txtEditCyl.Text = cylinders.ToString();
            txtEditBytesPerSector.Text = bytesPerSector.ToString();
            txtEditHds.Text = heads.ToString();
            txtEditSpt.Text = sectorsPerTrack.ToString();
            txtEditNewDefinedDrive.Text = name;

            cboComboDefinedDrives.SelectedText = name;
        }

        private void cboComboDefinedDrives_SelectedIndexChanged(object sender, EventArgs e)
        {
            //supportedWinchesterDrives
        }

        /*
            Thread t = new Thread
            ((ThreadStart)(() => 
                {
                        // put your STA apartment threaded code here
                        // do not reference any windows obects from this code
                        // only static local variables
                }
            ));

         * */

        private void BtnButtonBrowse_Click(object sender, EventArgs e)
        {
            string path = "";
            string filename = "";

            if (txtEditPath.Text.Length > 0)
            {
                path = Path.GetDirectoryName(txtEditPath.Text);
                filename = Path.GetFileName(txtEditPath.Text);
            }

            Thread t = new Thread
            ((ThreadStart)(() => 
                {
                    OpenFileDialog saveFileDialog1 = new OpenFileDialog();

                    OpenFileDialog ofd = new OpenFileDialog();
                    ofd.InitialDirectory = dataDir + path;
                    ofd.FileName = filename;

                    DialogResult dr = ofd.ShowDialog();
                    if (dr == DialogResult.OK)
                    {
                        path = ofd.FileName.Replace("\\", "/").Replace(dataDir, "");
                    }
                }
            ));

            t.SetApartmentState(ApartmentState.STA);
            t.Start();
            t.Join();

            txtEditPath.Text = path;
        }

        private void BtnButtonSaveDefinedDrive_Click(object sender, EventArgs e)
        {

        }
    }
}
