//This code has been automatically generated by DudeLabs, LLC RCConverter
using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;
namespace ConfigEditor
{
	/// <summary>
	/// Summary description for frmDialogHardDriveParameters.
	/// </summary>

	partial class frmDialogHardDriveParameters : System.Windows.Forms.Form
		{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.Container components = null;
        private System.Windows.Forms.TextBox txtEditCyl;
        private System.Windows.Forms.TextBox txtEditHds;
        private System.Windows.Forms.TextBox txtEditSpt;
        private System.Windows.Forms.TextBox txtEditLbaBlocks;
        private System.Windows.Forms.TextBox txtEditBytesPerSector;
        private System.Windows.Forms.ComboBox cboComboDefinedDrives;
        private System.Windows.Forms.TextBox txtEditNewDefinedDrive;
        private System.Windows.Forms.TextBox txtEditPath;
        private System.Windows.Forms.Button btnButtonSaveDefinedDrive;
        private System.Windows.Forms.Button btnButtonCancelDefinedDrive;
        private System.Windows.Forms.Label lblStatic1;
        private System.Windows.Forms.Label lblStatic2;
        private System.Windows.Forms.Label lblStatic3;
        private System.Windows.Forms.Label lblStatic4;
        private System.Windows.Forms.Label lblStatic5;
        private System.Windows.Forms.Label lblStaticImageLabel;
        private System.Windows.Forms.Button btnButtonBrowse;
        private System.Windows.Forms.Label lblStaticLbaBlocks;





		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if (components != null) 
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

					#region DudeLabs LLC RCConverter generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.txtEditCyl = new System.Windows.Forms.TextBox();
            this.txtEditHds = new System.Windows.Forms.TextBox();
            this.txtEditSpt = new System.Windows.Forms.TextBox();
            this.txtEditLbaBlocks = new System.Windows.Forms.TextBox();
            this.txtEditBytesPerSector = new System.Windows.Forms.TextBox();
            this.cboComboDefinedDrives = new System.Windows.Forms.ComboBox();
            this.txtEditNewDefinedDrive = new System.Windows.Forms.TextBox();
            this.txtEditPath = new System.Windows.Forms.TextBox();
            this.btnButtonSaveDefinedDrive = new System.Windows.Forms.Button();
            this.btnButtonCancelDefinedDrive = new System.Windows.Forms.Button();
            this.lblStatic1 = new System.Windows.Forms.Label();
            this.lblStatic2 = new System.Windows.Forms.Label();
            this.lblStatic3 = new System.Windows.Forms.Label();
            this.lblStatic4 = new System.Windows.Forms.Label();
            this.lblStatic5 = new System.Windows.Forms.Label();
            this.lblStaticImageLabel = new System.Windows.Forms.Label();
            this.btnButtonBrowse = new System.Windows.Forms.Button();
            this.lblStaticLbaBlocks = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // txtEditCyl
            // 
            this.txtEditCyl.Location = new System.Drawing.Point(116, 56);
            this.txtEditCyl.Name = "txtEditCyl";
            this.txtEditCyl.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditCyl.Size = new System.Drawing.Size(60, 20);
            this.txtEditCyl.TabIndex = 1;
            // 
            // txtEditHds
            // 
            this.txtEditHds.Location = new System.Drawing.Point(116, 82);
            this.txtEditHds.Name = "txtEditHds";
            this.txtEditHds.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditHds.Size = new System.Drawing.Size(60, 20);
            this.txtEditHds.TabIndex = 2;
            // 
            // txtEditSpt
            // 
            this.txtEditSpt.Location = new System.Drawing.Point(116, 107);
            this.txtEditSpt.Name = "txtEditSpt";
            this.txtEditSpt.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditSpt.Size = new System.Drawing.Size(60, 20);
            this.txtEditSpt.TabIndex = 3;
            // 
            // txtEditLbaBlocks
            // 
            this.txtEditLbaBlocks.Location = new System.Drawing.Point(296, 82);
            this.txtEditLbaBlocks.Name = "txtEditLbaBlocks";
            this.txtEditLbaBlocks.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditLbaBlocks.Size = new System.Drawing.Size(60, 20);
            this.txtEditLbaBlocks.TabIndex = 4;
            this.txtEditLbaBlocks.Visible = false;
            // 
            // txtEditBytesPerSector
            // 
            this.txtEditBytesPerSector.Location = new System.Drawing.Point(296, 107);
            this.txtEditBytesPerSector.Name = "txtEditBytesPerSector";
            this.txtEditBytesPerSector.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditBytesPerSector.Size = new System.Drawing.Size(60, 20);
            this.txtEditBytesPerSector.TabIndex = 5;
            // 
            // cboComboDefinedDrives
            // 
            this.cboComboDefinedDrives.Location = new System.Drawing.Point(186, 56);
            this.cboComboDefinedDrives.Name = "cboComboDefinedDrives";
            this.cboComboDefinedDrives.Size = new System.Drawing.Size(278, 21);
            this.cboComboDefinedDrives.Sorted = true;
            this.cboComboDefinedDrives.TabIndex = 6;
            this.cboComboDefinedDrives.SelectedIndexChanged += new System.EventHandler(this.cboComboDefinedDrives_SelectedIndexChanged);
            // 
            // txtEditNewDefinedDrive
            // 
            this.txtEditNewDefinedDrive.Location = new System.Drawing.Point(46, 146);
            this.txtEditNewDefinedDrive.Name = "txtEditNewDefinedDrive";
            this.txtEditNewDefinedDrive.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditNewDefinedDrive.Size = new System.Drawing.Size(240, 20);
            this.txtEditNewDefinedDrive.TabIndex = 7;
            // 
            // txtEditPath
            // 
            this.txtEditPath.Location = new System.Drawing.Point(110, 22);
            this.txtEditPath.Name = "txtEditPath";
            this.txtEditPath.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditPath.Size = new System.Drawing.Size(310, 20);
            this.txtEditPath.TabIndex = 8;
            // 
            // btnButtonSaveDefinedDrive
            // 
            this.btnButtonSaveDefinedDrive.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnButtonSaveDefinedDrive.Location = new System.Drawing.Point(300, 146);
            this.btnButtonSaveDefinedDrive.Name = "btnButtonSaveDefinedDrive";
            this.btnButtonSaveDefinedDrive.Size = new System.Drawing.Size(75, 24);
            this.btnButtonSaveDefinedDrive.TabIndex = 9;
            this.btnButtonSaveDefinedDrive.Text = "&Save";
            this.btnButtonSaveDefinedDrive.Click += new System.EventHandler(this.BtnButtonSaveDefinedDrive_Click);
            // 
            // btnButtonCancelDefinedDrive
            // 
            this.btnButtonCancelDefinedDrive.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnButtonCancelDefinedDrive.Location = new System.Drawing.Point(388, 146);
            this.btnButtonCancelDefinedDrive.Name = "btnButtonCancelDefinedDrive";
            this.btnButtonCancelDefinedDrive.Size = new System.Drawing.Size(75, 24);
            this.btnButtonCancelDefinedDrive.TabIndex = 10;
            this.btnButtonCancelDefinedDrive.Text = "&Cancel";
            // 
            // lblStatic1
            // 
            this.lblStatic1.AutoSize = true;
            this.lblStatic1.Location = new System.Drawing.Point(10, 61);
            this.lblStatic1.Name = "lblStatic1";
            this.lblStatic1.Size = new System.Drawing.Size(49, 13);
            this.lblStatic1.TabIndex = 11;
            this.lblStatic1.Text = "Cylinders";
            // 
            // lblStatic2
            // 
            this.lblStatic2.AutoSize = true;
            this.lblStatic2.Location = new System.Drawing.Point(10, 86);
            this.lblStatic2.Name = "lblStatic2";
            this.lblStatic2.Size = new System.Drawing.Size(38, 13);
            this.lblStatic2.TabIndex = 12;
            this.lblStatic2.Text = "Heads";
            // 
            // lblStatic3
            // 
            this.lblStatic3.AutoSize = true;
            this.lblStatic3.Location = new System.Drawing.Point(10, 112);
            this.lblStatic3.Name = "lblStatic3";
            this.lblStatic3.Size = new System.Drawing.Size(93, 13);
            this.lblStatic3.TabIndex = 13;
            this.lblStatic3.Text = "Sectors Per Track";
            // 
            // lblStatic4
            // 
            this.lblStatic4.AutoSize = true;
            this.lblStatic4.Location = new System.Drawing.Point(10, 152);
            this.lblStatic4.Name = "lblStatic4";
            this.lblStatic4.Size = new System.Drawing.Size(35, 13);
            this.lblStatic4.TabIndex = 14;
            this.lblStatic4.Text = "Name";
            // 
            // lblStatic5
            // 
            this.lblStatic5.AutoSize = true;
            this.lblStatic5.Location = new System.Drawing.Point(195, 112);
            this.lblStatic5.Name = "lblStatic5";
            this.lblStatic5.Size = new System.Drawing.Size(86, 13);
            this.lblStatic5.TabIndex = 15;
            this.lblStatic5.Text = "Bytes Per Sector";
            // 
            // lblStaticImageLabel
            // 
            this.lblStaticImageLabel.AutoSize = true;
            this.lblStaticImageLabel.Location = new System.Drawing.Point(10, 27);
            this.lblStaticImageLabel.Name = "lblStaticImageLabel";
            this.lblStaticImageLabel.Size = new System.Drawing.Size(93, 13);
            this.lblStaticImageLabel.TabIndex = 16;
            this.lblStaticImageLabel.Text = "Winchester Image";
            // 
            // btnButtonBrowse
            // 
            this.btnButtonBrowse.Location = new System.Drawing.Point(430, 22);
            this.btnButtonBrowse.Name = "btnButtonBrowse";
            this.btnButtonBrowse.Size = new System.Drawing.Size(33, 24);
            this.btnButtonBrowse.TabIndex = 17;
            this.btnButtonBrowse.Text = "...";
            this.btnButtonBrowse.Click += new System.EventHandler(this.BtnButtonBrowse_Click);
            // 
            // lblStaticLbaBlocks
            // 
            this.lblStaticLbaBlocks.AutoSize = true;
            this.lblStaticLbaBlocks.Location = new System.Drawing.Point(195, 86);
            this.lblStaticLbaBlocks.Name = "lblStaticLbaBlocks";
            this.lblStaticLbaBlocks.Size = new System.Drawing.Size(62, 13);
            this.lblStaticLbaBlocks.TabIndex = 18;
            this.lblStaticLbaBlocks.Text = "LBA Blocks";
            this.lblStaticLbaBlocks.Visible = false;
            // 
            // frmDialogHardDriveParameters
            // 
            this.ClientSize = new System.Drawing.Size(482, 188);
            this.Controls.Add(this.btnButtonSaveDefinedDrive);
            this.Controls.Add(this.btnButtonBrowse);
            this.Controls.Add(this.btnButtonCancelDefinedDrive);
            this.Controls.Add(this.cboComboDefinedDrives);
            this.Controls.Add(this.lblStatic1);
            this.Controls.Add(this.lblStatic2);
            this.Controls.Add(this.lblStatic3);
            this.Controls.Add(this.lblStatic4);
            this.Controls.Add(this.lblStatic5);
            this.Controls.Add(this.lblStaticImageLabel);
            this.Controls.Add(this.lblStaticLbaBlocks);
            this.Controls.Add(this.txtEditBytesPerSector);
            this.Controls.Add(this.txtEditCyl);
            this.Controls.Add(this.txtEditHds);
            this.Controls.Add(this.txtEditLbaBlocks);
            this.Controls.Add(this.txtEditNewDefinedDrive);
            this.Controls.Add(this.txtEditPath);
            this.Controls.Add(this.txtEditSpt);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Name = "frmDialogHardDriveParameters";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Winchester Add/Edit Dialog";
            this.Load += new System.EventHandler(this.frmDialogHardDriveParameters_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        } 
		#endregion

	}
}
