using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;

namespace ConfigEditor
{
    class KeyboardMapping
    {
        public Dictionary<string, string> keyboardMap = new Dictionary<string, string>
        {
            {"DeleteNormal"             , "^J"},
            {"DeleteShifted"            , ""  },
            {"DeleteControl"            , ""  },
            {"DeleteBoth"               , ""  },
            {"DownArrowNormal"          , "^C"},
            {"DownArrowShifted"         , ""  },
            {"DownArrowControl"         , "^N"},
            {"DownArrowBoth"            , ""  },
            {"EndNormal"                , "^]"},
            {"EndShifted"               , ""  },
            {"EndControl"               , "^B"},
            {"EndBoth"                  , ""  },
            {"HomeNormal"               , "^]"},
            {"HomeShifted"              , ""  },
            {"HomeControl"              , "^T"},
            {"HomeBoth"                 , ""  },
            {"InsertNormal"             , "^P"},
            {"InsertShifted"            , ""  },
            {"InsertControl"            , ""  },
            {"InsertBoth"               , ""  },
            {"LeftArrowNormal"          , "^S"},
            {"LeftArrowShifted"         , ""  },
            {"LeftArrowControl"         , "^A"},
            {"LeftArrowBoth"            , ""  },
            {"PadEightUpArrowNormal"    , "^E"},
            {"PadEightUpArrowShifted"   , ""  },
            {"PadEightUpArrowControl"   , "^Y"},
            {"PadEightUpArrowBoth"      , ""  },
            {"PadEnterNormal"           , "^M"},
            {"PadEnterShifted"          , ""  },
            {"PadEnterControl"          , ""  },
            {"PadEnterBoth"             , ""  },
            {"PadFourLeftArrowNormal"   , "^S"},
            {"PadFourLeftArrowShifted"  , ""  },
            {"PadFourLeftArrowControl"  , "^A"},
            {"PadFourLeftArrowBoth"     , ""  },
            {"PadFiveNormal"            , "^D"},
            {"PadFiveShifted"           , ""  },
            {"PadFiveControl"           , ""  },
            {"PadFiveBoth"              , ""  },
            {"PadNinePageUpNormal"      , "^R"},
            {"PadNinePageUpShifted"     , ""  },
            {"PadNinePageUpControl"     , ""  },
            {"PadNinePageUpBoth"        , ""  },
            {"PadOneEndNormal"          , "^]"},
            {"PadOneEndShifted"         , ""  },
            {"PadOneEndControl"         , "^B"},
            {"PadOneEndBoth"            , ""  },
            {"PadPeriodDeleteNormal"    , "^J"},
            {"PadPeriodDeleteShifted"   , ""  },
            {"PadPeriodDeleteControl"   , ""  },
            {"PadPeriodDeleteBoth"      , ""  },
            {"PadSevenHomeNormal"       , "^]"},
            {"PadSevenHomeShifted"      , ""  },
            {"PadSevenHomeControl"      , "^T"},
            {"PadSevenHomeBoth"         , ""  },
            {"PadSixRightArrowNormal"   , "^F"},
            {"PadSixRightArrowShifted"  , ""  },
            {"PadSixRightArrowControl"  , "^G"},
            {"PadSixRightArrowBoth"     , ""  },
            {"PadThreePageDownNormal"   , "^V"},
            {"PadThreePageDownShifted"  , ""  },
            {"PadThreePageDownControl"  , ""  },
            {"PadThreePageDownBoth"     , ""  },
            {"PadTwoDownArrowNormal"    , "^C"},
            {"PadTwoDownArrowShifted"   , ""  },
            {"PadTwoDownArrowControl"   , "^N"},
            {"PadTwoDownArrowBoth"      , ""  },
            {"PadZeroInsertNormal"      , "^P"},
            {"PadZeroInsertShifted"     , ""  },
            {"PadZeroInsertControl"     , ""  },
            {"PadZeroInsertBoth"        , ""  },
            {"PageDownNormal"           , "^V"},
            {"PageDownShifted"          , ""  },
            {"PageDownControl"          , ""  },
            {"PageDownBoth"             , ""  },
            {"PageUpNormal"             , "^R"},
            {"PageUpShifted"            , ""  },
            {"PageUpControl"            , ""  },
            {"PageUpBoth"               , ""  },
            {"RightArrowNormal"         , "^F"},
            {"RightArrowShifted"        , ""  },
            {"RightArrowControl"        , "^G"},
            {"RightArrowBoth"           , ""  },
            {"UpArrowNormal"            , "^E"},
            {"UpArrowShifted"           , ""  },
            {"UpArrowControl"           , "^Y"},
            {"UpArrowBoth"              , ""  }
        };
    }
}
